const questionBank = [
  'What type of contest would **name** win between all the people in the room?',
  'What does **name** know more about than anyone else in the room?',
  'What is the best gift **name** has ever received?',
  'What tv gameshow would **name** most like to be on?',
  'Which Disney character would **name** want to hang out with?',
  'What is the weirdest thing **name** has ever eaten?',
  'What emoji does **name** use most?',
  "Who would play **name** in a movie about **name**'s life?",
  "What is **name**'s least favorite food?",
  'If **name** could add anyone to Mount Rushmore, who would it be?',
  "If **name**'s hands were animals, what animal would **name** choose?",
  'If **name** had to teach a class on something, what would **name** teach?',
  'What song does **name** belt out loud when no one else is listening?',
  "What is something **name** wouldn't do for $1,000,000?",
  "What is **name**'s dream job?",
  "What is **name**'s biggest fear?",
  'If **name** could live in any time period, when would it be?',
  'If The World Froze For An Afternoon And Only **name** Could Move And No One Could See Or Remember What **name** Did, What Would **name** Do?',
  'What’s the last concert **name** went to?',
  "What is **name**'s spirit animal?",
  'What can **name** not live without?',
  'If **name** could meet one person from any point in history, who would **name** choose?',
  "What is **name**'s hidden talent?",
  'If **name** could choose any superpower, what would it be?',
  'What is the first thing **name** would buy after winning the lottery?',
  'Where would **name** go on vacation if time/money were not a consideration?',
  'If **name** could only eat one type of food, what would it be?',
];

module.exports = questionBank;
